### ISSUE TITLE
Error while running authentication service

### ISSUE THREAD

**Issue by Yogi-Vishwas** [sourcefuse/loopback4-microservice-catalog#1043]
**Describe the bug**
When user runs the authentication service error is thrown.
**To Reproduce**
1. run sl microservices
2. select yes for base service
3. Select yes for migrations 
4. Select include migrations from base service
5. First it throws the error reported in issue #1041 
6. user creates and runs the migrations manually  
7. npm start

**Expected behavior**
server should be up and running but the error is thrown instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/107536993/194534793-2def2224-ec11-4d4f-b59b-abf85b2b9890.png)

**Additional context**
I fixed the error by manually navigating to the problem source and entered the url.

**Comment by yeshamavani** [comment]
hi @Yogi-Vishwas couldnot reproduce this error. let me know when can we connect to check this one.

**Comment by yeshamavani** [comment]
@Yogi-Vishwas closing this issue.
