### ISSUE TITLE
User Tenant service has in models some extra properties for tenant table. 

### ISSUE THREAD

**Issue by gautam23-sf** [sourcefuse/loopback4-microservice-catalog#1073]
**Describe the bug**
User Tenant service uses the AuthDB, but there are some extra properties defined for tenants table in user service.

**Expected behaviour**
Model in user tenant service must be consistent with the Auth service Model. 

**Screenshot**
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/108651274/200821641-990bfeda-452b-461e-9144-39eb59e15350.png">

**Comment by Tyagi-Sunny** [comment]
The issue will be resolved via #1696
