### ISSUE TITLE
@sourceloop/cli : no proper error when command run in wrong folder

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1096]
**Describe the bug**
Very vague error description when sl microservice command is run in a wrong folder

**To Reproduce**
1. Run sl scaffold test
2. Dont change the working directory to test (cd test) 
3. Run sl microservice

**Expected behavior**
A clear and understandable error message should be shown

**Screenshots**

![image](https://user-images.githubusercontent.com/83634146/203321356-afdd7059-b555-4a45-87aa-dcca6fb5cc2e.png)

**Comment by Tyagi-Sunny** [comment]
![image](https://github.com/user-attachments/assets/6f8fa539-7118-4843-8691-edb90ae871f0)
clear and understanble message is coming. so we are closing this issue
