### ISSUE TITLE
@sourceloop/cli: Common Error whenever we run any command through cli.

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1199]
**Describe the bug**
Common Error whenever we run any command through cli.

**To Reproduce**
1. Run a sl cli command.
2. something like sl scaffold
3. Observe the error.

**Expected behavior**
No error message should be shown when the command is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/83634146/212607379-7e09805c-e261-4928-a989-978b2cc22798.png)

**Comment by shubhamp-sf** [comment]
Closed by https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1379
