### ISSUE TITLE
Fix the documentation of the user-tenant service

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1201]
**Describe the bug**
Fix the documentation of the user-tenant service
The node 12 support .

**Comment by shubhamp-sf** [comment]
@yeshamavani can we assign this to someone else? who knows this service usage.

**Comment by shubhamp-sf** [comment]
Moving it here: https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1440
