### ISSUE TITLE
@sourceloop/cli : Change the documentation and make it user friendly

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1215]
**Describe the bug**
The sl cli readme file is too technical.
It is autogenerated.
Find a way to mak eit more detailed and helpful.

link : https://www.npmjs.com/package/@sourceloop/cli

**Comment by shubhamp-sf** [comment]
Moving it here along with all other docs improvements: https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1440
