### ISSUE TITLE
Require paypal payment gateway in payment-service

### ISSUE THREAD

**Issue by sf-vikrant** [sourcefuse/loopback4-microservice-catalog#1367]
**Is your feature request related to a problem? Please describe.**
No, it is a new feature

**Describe the solution you'd like**
We would like to have Paypal as a payment gateway similar to as Stripe payment gateway in source-loop payment-service
We also require to support credit card payments

**Describe alternatives you've considered**
Implement Paypal payment gateway on own

**Comment by shubhamp-sf** [comment]
Closed by https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1389
