### ISSUE TITLE
Audit log mixin needs to be added in sourceloop services

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1368]
**Is your feature request related to a problem? Please describe.**
 No, it is a new feature

**Describe the solution you'd like**
We should be able to save audit log for following services:
1. Video conferencing service
2. authentication service
3. user-tenant service
4. chat service
5. scheduler service

**Comment by shubhamp-sf** [comment]
@samarpan-b sir, chat-service already have a [db level triggers in migrations](https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/chat-service/migrations/sqls/20201103141746-init-script-up.sql#L93-L95) that stores audit logs by default.
<img width="1391" alt="Screenshot 2023-04-13 at 5 21 43 PM" src="https://user-images.githubusercontent.com/110156023/231750143-c2711123-8b2f-4341-953e-369bd41cd459.png">

Should this behaviour be replaced?

**Comment by shubhamp-sf** [comment]
Reopening as only video-conferencing service is done with the changes.
