### ISSUE TITLE
Overlapping permissions in base services

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1381]
**Describe the bug**
Api permissions in base services are overlapping.
for example:
1. chat service have permission value starting as 1 in enum and in scheduler service as well permission starting from 1
Impact:
If I have to give user A permission to view chat only than user A will get permission to view calendar as well or vice-versa.

Reference to validate:
1. chat service> model > enum > permissions
2. scheduler-service > model > enum > permissions

**Expected behavior**
Permissions should not overlap.

**Screenshots**
![Screenshot(69)](https://user-images.githubusercontent.com/109057508/232491973-c621a50c-8f03-4d7c-a23e-ec0f043ce7f0.png)
![Screenshot(68)](https://user-images.githubusercontent.com/109057508/232491983-b051ecca-75fb-43a5-865c-46de262303a9.png)
![Screenshot(67)](https://user-images.githubusercontent.com/109057508/232491988-109a103d-45fe-4340-a226-2c489d93285f.png)

**Additional context**

**Comment by sadarunnisa-sf** [comment]
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/payment-service/src/enums/permission-key.enum.ts

https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/notification-service/src/enums/permission-key.enum.ts

https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/user-tenant-service/src/enums/permission-key.enum.ts
 Same for above services as well

**Comment by shubhamp-sf** [comment]
Fixed by https://github.com/sourcefuse/loopback4-authorization/pull/96
