### ISSUE TITLE
Loopback and Sourceloop version update

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1392]
**Describe the bug**
Loopback and Sourceloop version update

**To Reproduce**
1. Currently all services refering to an older version.
2. Check the package.json and package-lock.json files to verify

**Expected behavior**
Should refer to the latest versions.

**Comment by shubhamp-sf** [comment]
Closed by https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1393
