### ISSUE TITLE
Ability to skip logging ping requests

### ISSUE THREAD

**Issue by prernagp** [sourcefuse/loopback4-microservice-catalog#1429]
**Is your feature request related to a problem? Please describe.**
Currently, there are a lot of ping requests being logged, so there should be the ability to skip logging ping requests. 

**Describe the solution you'd like**
A flag that can control to log ping requests or not.

**Describe alternatives you've considered**
Created a custom logger sequence and bypassed the ping requests.

**Comment by RaghavaroraSF** [comment]
Hii @prernagp 
from my POV,
If we set LOG_LEVEL= error in env ,
it already skips the logging ping requests, so try this and do let me know if its not working.

**Comment by yeshamavani** [comment]
@prernagp  can we close this issue 
does the above comment by raghav help you or is anything pending

**Comment by prernagp** [comment]
@yeshamavani It worked using the said flag. We can close this ticket

**Comment by yeshamavani** [comment]
Thanks @prernagp
