### ISSUE TITLE
Need a way to hide some of the APIs of a microservice if not needed

### ISSUE THREAD

**Issue by samarpan-b** [sourcefuse/loopback4-microservice-catalog#143]
**Is your feature request related to a problem? Please describe.**
There needs to be some way of configuring some APIs to be hidden or not required. If configured so, then, they should not show up in open api spec for the same.

**Describe the solution you'd like**
Some configuration needed. Not sure what's the best way. Is there a way to make an api hidden in open api spec ?

**Describe alternatives you've considered**
None as of now

**Additional context**
Might be related -> https://github.com/OAI/OpenAPI-Specification/issues/433

**Comment by samarpan-b** [comment]
@sourcefuse/sourceloop thoughts ?

**Comment by akshatdubeysf** [comment]
@sachin6161

**Comment by samarpan-b** [comment]
Fixed with https://github.com/sourcefuse/loopback4-microservice-catalog/pull/364
