### ISSUE TITLE
GA Milestone - April 2021 

### ISSUE THREAD

**Issue by samarpan-b** [sourcefuse/loopback4-microservice-catalog#150]
# GA Milestone

List of items to achieve before we can make Sourceloop GA

- [x] Automate database migration when a micro service is installed or updated (#124)
- [x] Need examples for each microservice (#146)

Above is bare minimum list before we go for GA. We need opinions on what else is needed. @sourcefuse/sourceloop

**Comment by mlakdawala-sf** [comment]
multiple starter recipes built upon sourceloop, consuming services ??

**Comment by samarpan-b** [comment]
@mlakdawala-sf do you think we can add to examples as mentioned here - https://github.com/sourcefuse/loopback4-microservice-catalog/issues/146 ?

**Comment by akshatdubeysf** [comment]
Examples and version updates done, hence closing this issue.
