### ISSUE TITLE
Add Configuration to also show only search result overlay without search input box

### ISSUE THREAD

**Issue by amitparsha** [sourcefuse/loopback4-microservice-catalog#1561]
**Is your feature request related to a problem? Please describe.**

Currently search-client contains search input and show result overlay when user input some element, but there is no any configuration to show only the result overlay without search input box with some custom search event configuration

**Describe the solution you'd like**

- Configuration to show only result overlay without search input box
- we can pass some configuration like custom search event with model name, search value etc. 
- So, in this way it will be useful in micro frontend application as consider an example
- header module which contains search input box as one micro frontend and other micro frontend module  which communicates with search input through event bus communication can able to show only the result overlay

**Comment by shubhamp-sf** [comment]
Closed in #1562
