### ISSUE TITLE
Redundant `posttest` script in all packages

### ISSUE THREAD

**Issue by shubhamp-sf** [sourcefuse/loopback4-microservice-catalog#1657]
All packages/services in this repo contains a `posttest` script that executes `npm run lint`.

In our CI process we have tests and linting separate so when test step runs it automatically executing linting as well. So the extra lint step is redundant there.

We should either removing that step from CI or trim this posttest scripts from everywhere.

Since linting and running test cases are development only workflow and treated separate, we should ideally remove the post test script from `package.json` of all packages.

<img width="774" alt="Screenshot" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/110156023/3d7442bd-3d2e-488e-8e68-8e2dbe94c92c">

**Comment by shubhamp-sf** [comment]
> posttest script ensures that properly lint code is committed

For that we can add another command below this line:

https://github.com/sourcefuse/loopback4-microservice-catalog/blob/0b8b35e22118978752c80d119b9e3dd040b9e7b4/.husky/pre-commit#L4

Just so that things are predictable and we're not tailing two separate processes.

**Comment by yeshamavani** [comment]
> > posttest script ensures that properly lint code is committed
> 
> For that we can add another command below this line:
> 
> https://github.com/sourcefuse/loopback4-microservice-catalog/blob/0b8b35e22118978752c80d119b9e3dd040b9e7b4/.husky/pre-commit#L4
> 
> Just so that things are predictable and we're not tailing two separate processes.

works!!
