### ISSUE TITLE
Search component css color is hardcoded

### ISSUE THREAD

**Issue by mlakdawala-sf** [sourcefuse/loopback4-microservice-catalog#1665]
**Describe the bug**
Search component css color is hardcoded and difficult to customise 

**Expected behavior**
Components should be extensible to design changes easily, the problem is important is written for multiple properties hence we cannot change anything as per requirement

**Screenshots**
<img width="1440" alt="image" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/73096294/89176830-ddee-4d1d-8733-60b49cf922dd">

**Comment by shubhamlalsourcefuse** [comment]
It's working now.
Thanks @arpit1503khanna.

**Comment by yeshamavani** [comment]
This is to be moved to ng-components
