### ISSUE TITLE
Add null check in Search Client Package on search with custom search event

### ISSUE THREAD

**Issue by amitparsha** [sourcefuse/loopback4-microservice-catalog#1674]
**Describe the bug**
With Search Client package
 1.  on search with custom search event for the first time user face the error as below in screenshot (No Columns To Match)
 2. the api calls with 'sources' in payload as below 
 {"match":"hello","sources":[null],"limit":5,"limitByType":true,"order":"","offset":0}

**To Reproduce**
1. Use the search client with custom search event and for the first time user will face the error (No columns to Match) 

**Expected behavior**
there should be no error and api payload should be like this 
 {"match":"hello","sources":[],"limit":5,"limitByType":true,"order":"","offset":0}
or sources array should map with some values

**Screenshots**
![image](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/60221425/2e853cad-7549-4eb1-9f36-f151e36b2030)

**Comment by shubhamp-sf** [comment]
Fixed by #1675
