### ISSUE TITLE
Search Element: Icons are not getting loaded into react application.

### ISSUE THREAD

**Issue by shubhamlalsourcefuse** [sourcefuse/loopback4-microservice-catalog#1697]
**Describe the bug**
Failure of icons to load within a React application when search element is implemented as a web component. Despite the successful integration of the web component, the expected icons within the component do not render as intended.

**Expected behavior**
Icon should be displayed properly into search box, button and option menus

**Screenshots**
<img width="770" alt="image" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/125964482/36c3e216-47ee-4ac2-8515-15a964d9822d">

**Comment by yeshamavani** [comment]
Was done changes needed to be done in the react app
