### ISSUE TITLE
Sandbox is broken

### ISSUE THREAD

**Issue by SF-pliebscher** [sourcefuse/loopback4-microservice-catalog#1723]
**Describe the bug**
Sandbox is broken.

**To Reproduce**
1. Go to the ['Sandbox'](https://sourcefuse.github.io/arc-docs/arc-api-docs/sandbox/)
2. Try in Firefox
3. Try in Chrome
4. Try in Edge

**Expected behavior**
A working sandbox

**Screenshots**
![image](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/144848549/9bea542a-5cd7-40e2-8dc4-0007f75eabc2)

**Comment by yeshamavani** [comment]
We dont have any docs for sandbox on our github pages
<img width="1240" alt="image" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/83634146/2ee7870d-2c14-4dec-9957-e999c0b49ec2">
