### ISSUE TITLE
User Onboarding Microservice

### ISSUE THREAD

**Issue by samarpan-b** [sourcefuse/loopback4-microservice-catalog#173]
**Is your feature request related to a problem? Please describe.**
There is always a need for a reusable user onboarding or user guide feature in every application. It will be a very good addition to this catalog.

**Describe the solution you'd like**
@kabir-chandhoke to add.

**Comment by samarpan-b** [comment]
@akshatdubeysf can you add the requirement doc and TDD here please ?

**Comment by akshatdubeysf** [comment]
Requirement Document - [SourceLoop Onboarding and Help Microservice.docx](https://github.com/sourcefuse/loopback4-microservice-catalog/files/6377086/SourceLoop.Onboarding.and.Help.Microservice.docx)

TDD - [Technical Design Document (TDD) template for Sourceloop Onboarding and Help Microservice.docx](https://github.com/sourcefuse/loopback4-microservice-catalog/files/6377088/Technical.Design.Document.TDD.template.for.Sourceloop.Onboarding.and.Help.Microservice.docx)
