### ISSUE TITLE
base migration not getting loaded for survey-service

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1811]
**Describe the bug**
On setting up micro-service using survey service of sl services as base , migration script not getting loaded.

**To Reproduce**
1. setup sl microservice using survey-service as base
2. say yes to load migrations
3. migration run script added in package json but no SQL script or folder added in migrations.

**Expected behavior**
1. survey-service should load sql migration scripts.

**Screenshots**
![Screenshot from 2023-11-17 14-59-41](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/109057508/789acb8a-dd01-4a97-b898-a0bec4da883b)

**Additional context**

node version: 18.18.1
sl version: 5.0.0

**Comment by yeshamavani** [comment]
Solved with https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1805
