### ISSUE TITLE
@sourceloop/search-client: Update version of dependencies 

### ISSUE THREAD

**Issue by Chahat-Chugh** [sourcefuse/loopback4-microservice-catalog#1817]
**Is your feature request related to a problem? Please describe.**
Facing issue in installing sourceloop search client due to conflict in version of dependencies. Our project uses angular 14.

**Describe the solution you'd like**
Update version of angular and corresponding dependencies

**Comment by yeshamavani** [comment]
Moved this issue to its respective repository - https://github.com/sourcefuse/arc-ng-components/issues/9
