### ISSUE TITLE
All services : Add support for mysql migrations in all services

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1836]
**Is your feature request related to a problem? Please describe.**
Right now we only provide postgres migrations and it is difficult for people opting for mysql 
as they have to create their own scripts to execute.

**Describe the solution you'd like**
A separate set of migrations for mysql database.

**Comment by Pushpak562** [comment]
Services Impacted

1. Notification - **Done**
2. Chat - **WIP**
3. Audit
4. Authentication
5. Feature Toggle
6. Payment
7. Search
8. Survey
9. Task
10. User tenant
11. Video conferencing
12. Scheduler
13. BPMN
14. OIDC
15. In-Mail
16. Reporting
