### ISSUE TITLE
Authentication Service: Need support to manage tokens for user logging in via Facebook

### ISSUE THREAD

**Issue by arpit1503khanna** [sourcefuse/loopback4-microservice-catalog#1894]
**Describe the bug**
When a user logs in via facebook , the tokens provided by the facebook are not used , while issuing access tokens tokens using the refresh token. Instead the tokens are internally generated without any consent from facebook
in continuation - #1263

**Comment by yeshamavani** [comment]
No one working on this refer the parent issue, for now closing this
