### ISSUE TITLE
read values from ssm instead of reading directly from env file while performing lambda based deployment 

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1926]
**Is your feature request related to a problem? Please describe.**
Currently, whenever we do lambda based deployment we read values for env keys directly from the environment variables but ideally, it should read from ssm

**Describe the solution you'd like**
While doing cdk deployment read the values from aws ssm, in the env file it should have a reference only for that key but ideally, the value of that key should be read from aws ssm only.

**Comment by prernagp** [comment]
this issue is resolved via https://github.com/sourcefuse/arc-cdk/issues/47

**Comment by yeshamavani** [comment]
closing since resolved via https://github.com/sourcefuse/arc-cdk/issues/47
