### ISSUE TITLE
save terrafrom state file in s3 after completing lambda based deployement for service

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1927]
**Is your feature request related to a problem? Please describe.**
Currently whenever any deployment happen from local system state file fo terraform stays in local system from where the deployment were initiated.
But if that user or system is not available other person cannot do deployment without state file or by without destroying file reference on terraform manually.

**Describe the solution you'd like**
By default, once the deployment of any service is completed and the image is pushed in the server it should upload that terraform state file into s3 bucket as well.
Similarly if any other user is doing deployment it should fetch that state file from s3 as well to make deployment independent of user or state file.

**Comment by prernagp** [comment]
this has been resolved via https://github.com/sourcefuse/arc-cdk/issues/52

**Comment by yeshamavani** [comment]
closing since resolved via https://github.com/sourcefuse/arc-cdk/issues/52
