### ISSUE TITLE
Move the API logic of controllers, which is currently implemented in the controller, to the service file, please.

### ISSUE THREAD

**Issue by Akanksha13-dev** [sourcefuse/loopback4-microservice-catalog#1949]
Few controlers like..
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/survey-service/src/controllers/survey-responder.controller.ts
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/survey-service/src/controllers/survey-response.controller.ts
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/survey-service/src/controllers/survey-question.controller.ts
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/survey-service/src/controllers/survey-cycle.controller.ts
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/survey-service/src/controllers/section.controller.ts

**Comment by yeshamavani** [comment]
@Akanksha13-dev would you like to contribute
