### ISSUE TITLE
Cognito logout featur required

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1997]
**Is your feature request related to a problem? Please describe.**
When users logged in through Cognito need to log out, we face an issue as the current logout API only supports logging out users who have logged in using internal authentication, not through any other OAuth like Cognito.

The problem arises when a user logs in and then logs out of the system, but the session is still active at the Cognito end. This can cause confusion if the user is not correctly logged out from all authentication platforms, such as Cognito and the internal database. The user may not experience a normal login flow, which can lead to confusion.

**Describe the solution you'd like**
There should be cognito logout API available which will logout current user session on cognito platform as well.
This API should be independent of any other system should be use only to logout from cognito.

As making it independent will help user to write his own BL around it. Or handling other scenarios as well.

**Describe alternatives you've considered**
use cognito submethod provided to logout or use cognito API that accept current use refresh and access token to logout

**Comment by yeshamavani** [comment]
@arpit1503khanna I guess this is done as a part of your change for https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1943 can you please confirm and change the status of this issue

**Comment by arpit1503khanna** [comment]
@sumit-singhania can u please confirm if the issue is still there. Some changes were made to address this issue

**Comment by yeshamavani** [comment]
Closing this as it is already done. if there are any further changes required feel free to open a new issue or reopen this one.
