### ISSUE TITLE
Cognito change password feature required

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1998]
**Is your feature request related to a problem? Please describe.**
It is necessary to have a "change password" feature in sourceloop Cognito API. When a logged-in user tries to change their password, they should be able to change it both within the system and on the Cognito platform.

Currently, if the password is changed using the internal "change password" API, the user who interacts with the Cognito page first will not see the updated password. This means that although the user has changed their password by logging into the system and using the feature, it will not be updated in the Cognito platform.

**Describe the solution you'd like**
use cognito.changePassword method provided by CognitoIdentityServiceProvider as we  don't have direct API of change password  available in documentation.

Although there is provision of doing same through API as well but end point is not directly available.

So you can opt for any approach if you are able to find end point that will be better approach.

**Describe alternatives you've considered**
We have used currently cognito.changePassword method

**Additional context**
This action should be either independent so any BL can be implemented around it or it should be performed first than internal system change password, As we have to make sure internal system password only change when we are able to successfully update password on cognito

**Comment by samarpan-b** [comment]
I dont agree with this request. Since we are using cognito as IDP, so we intentionally dont want to manage its passwords. You should redirect user to cognito  to change his own password there.

**Comment by sumit-singhania** [comment]
Yes cognito allow change password through UI , when you are on login or forget password screen of cognito.

But in case when already know your password and want change it after login into your profile and by change password feature.
In that case you cannot redirect user to cognito screen again as change password based on existing password cognito either allow through cli or API for that user-pool.

Also in the scenario like : tomorrow for xy reason I change my idp from cognito to other one or remove even the idp and directly use sourceloop authentication APIs , so in that case do we have to send every registered user temporary password again to reset and login

**Comment by samarpan-b** [comment]
> But in case when already know your password and want change it after login into your profile and by change password feature.
This is anti pattern and is a security issue. You should never store password if you are not IDP.

**Comment by sumit-singhania** [comment]
**This is anti pattern and is a security issue. You should never store password if you are not IDP.**

Agreed if we are not IDP we should not store , but we should change password at IDP when user request or that is also not correct?

And currently the reference we had for this was through the api provided by cognito or through CLI.

Do we have any UI reference as well where we can redirect user to UI for this particular part

**Comment by samarpan-b** [comment]
No @sumit-singhania we should not manage passwords at all when we are not IDP. We should simply redirect user to IDP for these actions.

**Comment by yeshamavani** [comment]
closing this as well.. this is an anti-pattern
