### ISSUE TITLE
Creditianl exposure issue in cognito and keycloak login api

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#2001]
**Describe the bug**
Login api or cognito and keycloak ask for client_id and client_Secret , which is wrong ideally it should ask for some other uid or constant key that reference further to these creds.

As these creds are directly getting exposed through these api's , it can be used to manipulate other user data or getting access to user data corresponding to that client id
**To Reproduce**
1. go to authentication service
2. run swagger
3. check auth/cognito OR auth/facebook or auth/keycloak
4. if you see all are accepting payload as client id and client secret, although we have post request as well but anyhow man in the middle get request body he will get these creds as well

**Expected behavior**
ideally it should take some uid or constant value referenced to these creds and that id should not be linked to any other table in any way such that cannot be used against us

**Screenshots**
<img width="913" alt="Screenshot 2024-02-21 at 1 16 31 PM" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/109057508/610e7055-f4b2-4739-ac52-5fdcbc4296d6">

**Comment by samarpan-b** [comment]
Its a POST API and its taking information in body, so its not a security issue. Moreover, this can happen with any other mechanism as well. Even with your suggested solution.

**Comment by yeshamavani** [comment]
Here we have updated our client_password strategy that doesnot require client secret in case of public clients so you can try that. Have a look at this example https://github.com/sourcefuse/loopback4-microservice-catalog/tree/master/sandbox/auth-public-private-client
