### ISSUE TITLE
Update migration.js for every service

### ISSUE THREAD

**Issue by Tyagi-Sunny** [sourcefuse/loopback4-microservice-catalog#2003]
**Describe the bug**
User not able to generate migration manually as mentioned in readme
![image](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/107617248/ac161161-a7ce-467d-930d-e4b4ffb88c32)

**To Reproduce**
1. create a lb4 app
2. follow the readme to implement service
3. do npm i

**Expected behavior**
migration should be created after doing npm i automatically

**Screenshots**
but getting above added error

**Comment by yeshamavani** [comment]
@Tyagi-Sunny please describe this issue in brief
