### ISSUE TITLE
Add patch api in task service to update any tasks.

### ISSUE THREAD

**Issue by Dinu-1099** [sourcefuse/loopback4-microservice-catalog#2032]
**Is your feature request related to a problem? Please describe.**
I need to update a task priority or task status or any other field for a task there is no such api exists in task service.

**Describe the solution you'd like**
A patch api should be there in task service to update any task.

**Comment by yeshamavani** [comment]
@rahulvsf any specific reason why this was not the part the initial draft 
cc- @samarpan-b @a-ganguly

**Comment by rahulvsf** [comment]
> @rahulvsf any specific reason why this was not the part the initial draft cc- @samarpan-b @a-ganguly

No specific reason, but we had a POST api which would move the workflow user tasks ahead through a task processor command, which would update the task in db. The whole essence of workflow is to allow for automation and let it update by itself. If the user has to patch then it should be inactive in BPMN engine (after the task has moved from active to inactive state).

**Comment by yeshamavani** [comment]
@Dinu-1099 why do you wish to manually call the patch API

**Comment by Dinu-1099** [comment]
> @Dinu-1099 why do you wish to manually call the patch API

We have a requirement to update the task priority and mark the task as complete under certain conditions. I understand that for completing the task, we have a POST API available, which can be utilized. However, for updating other fields of a task, such as in my case where I need to update the task priority based on certain conditions, we need these APIs in task service.

**Comment by akshatdubeysf** [comment]
@samarpan-b @rahulvsf there could be cases where we are doing this as part of a command, but that command is running in different pod/service, and hence it would need a way to update the tasks through an API

**Comment by samarpan-b** [comment]
Ok thanks.
