### ISSUE TITLE
Follow SOLID 

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#2037]
**Describe the bug**
Remove the logic from the repositories and move it to a separate service.
Also add the test cases wherever necessary.

eg :- https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/authentication-service/src/repositories/user.repository.ts 

**To Reproduce**

**Expected behavior**
We should follow SOLID and repositories should not have business logic within them.

**Screenshots**

**Additional context**

**Comment by namandeep-s1ngh** [comment]
repositories to be updated: 
1. authentication service > user.repository.ts
2. in-mail-service > message.repository.ts, thread.repository.ts
3. oidc service > user.repository.ts
4. search-service > recent-search.repository.ts, search-query.repository.ts
5. survey-service > section.repository.ts, survey-question.repository.ts, survey-responder.repository.ts 
6. user-tenant-service > user.repository.ts

Along with these, the respective sanbox examples will also be updated.

**Comment by namandeep-s1ngh** [comment]
sandbox examples to be updated: 
1. auth-ms-basic-example > user.repository.ts
2. auth-multitenant-example > user-ext.repository.ts
3. oauth-example > user.repository.ts
4. telemed-app > backend > authentication-service > user.repository.ts
