### ISSUE TITLE
Need an example for pubnub as a provider in Notification service

### ISSUE THREAD

**Issue by SouravSF** [sourcefuse/loopback4-microservice-catalog#208]
I went through the examples and found that we presently do not have pubnub as a provider in any of our examples.
therefore, it would be resourceful to have an example with pubnub as a provider.

While creating the implementation I would request you to consider, Access management for channel subscriptions. posting messages to channels/channel groups.
for permission flow please consider https://www.pubnub.com/docs/security/access-control#initialize-with-secretkey

it would be an added advatage if we can also have a built in capability of monitoring presence at the service end where we use the pubnub webhooks to monitor users presence,
This might be a SRP breach but putting it here would kind of wrap the pubnub implementation at one place and accelerate the development.

**Comment by akshatdubeysf** [comment]
@sumiter92
