### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#211]
**Describe the bug**
The documentation is not clear and complete in the current state.

**Expected behavior**
The documentation should be clear and easy to understand, for all the services and examples.

**Services**
- [x] Audit Service - @sumiter92 
- [x] Authentication Service - @akshatdubeysf 
- [x] BPMN Service - @akshatdubeysf 
- [x] In-mail Service - @sumiter92 
- [x] Notification Service - @yeshamavani 
- [x] Scheduler Service - @ashutosh-bansal-2136 
- [x] Video Conferencing Service - @ashutosh-bansal-2136 

**Examples**

- [ ] Audit Example
- [ ] Auth Basic MS Example
- [ ] Auth Multitenant Example
- [ ] In-mail Example
- [ ] Notification Socket Example
- [ ] Scheduler Example
- [ ] Video-conferencing Example
- [ ] Workflow Example

**Comment by akshatdubeysf** [comment]
@sumiter92

**Comment by samarpan-b** [comment]
We also need to replace mention of loopback4-microservices-catalog with Sourceloop, all through the readmes. Also add link to https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/DEVELOPING.md in root readme

**Comment by akshatdubeysf** [comment]
@harshitmitSF can you check this comment now?

**Comment by harshitmitSF** [comment]
> @harshitmitSF can you check this comment now?

yes sir
