### ISSUE TITLE
Stipe payment gateway service

### ISSUE THREAD

**Issue by anujkalka** [sourcefuse/loopback4-microservice-catalog#212]
**Is your feature request related to a problem? Please describe.**
General stripe payment gateway service

**Describe the solution you'd like**

Should have ability to 
1 - Add customer
2 -  Add credit card/debit card to the customer
3 -  Add bank accounts to customer
4 -  Charge customer creditcard
5 - Make bank transfer to customer
6 - Validate payment methods
6 - Refunds
7 - Transaction history
8 - Support DB transactions with rollback feature in the event of error

**Comment by SouravSF** [comment]
@anujkalka Do u want to store the CC as part of microservice or any other third partycan keep it? cause it would need PCI certification IMO.
