### ISSUE TITLE
@sourceloop/authentication-service: Error: No factory found for sf.passport.strategyFactory.localPassword

### ISSUE THREAD

**Issue by Sumit9669** [sourcefuse/loopback4-microservice-catalog#2157]
**Describe the bug**
when using authentication service APIs to login getting following error:
Error: No factory found for sf.passport.strategyFactory.localPassword

API checked: auth/login(Error: No factory found for sf.passport.strategyFactory.localPassword)
auth/login-token(Error: No factory found for sf.passport.strategyFactory.ResourceOwner)

**To Reproduce**
1. setup authentication microservice using sourceloop CLI.
2. create user through migration or manual
3. hit Login API 

**Expected behavior**
user should be able to login successfully and it should return token to access to other resources

**Screenshots**
![Capture254](https://github.com/user-attachments/assets/fdd28b14-7794-4e4c-b7e6-297a9b79d246)

**Additional context**
loopback cli: 6.0.0
sourceloop cli: 9.0.2
node:18.20.4
lerna 5.2.4

**Comment by yeshamavani** [comment]
Hello @Sumit9669 the Local Passport strategy is not a mandatory strategy its an optional feature 
so to use that you are required to bind the strategy to its provider. ou can refer the docs [here](https://github.com/sourcefuse/loopback4-authentication?tab=readme-ov-file#local)

**Comment by Sumit9669** [comment]
@yeshamavani thanks for responding but i had tried this as well earlier but were getting same issue.

Apart from that in following scenario everything works fine:
sourceloop/cli: 4.2.0
node: 16.5
lerna : 5.4.2
authentication-service: v9.1.2

**Comment by yeshamavani** [comment]
> @yeshamavani thanks for responding but i had tried this as well earlier but were getting same issue.
> 
> Apart from that in following scenario everything works fine: sourceloop/cli: 4.2.0 node: 16.5 lerna : 5.4.2 authentication-service: v9.1.2

The strategy factory and its related binding needs to be provided after binding the component 
Can you please confirm if you have done it that way.

**Comment by yeshamavani** [comment]
@Sumit9669 is it working for you

**Comment by Sumit9669** [comment]
> it is resolved. After providing required binding.

@prernagp @yeshamavani  that time we were not able to solve it after providing binding, so we moved to lower version as we were on fast faced. For now you can close this issue, after updating dependencies if still breaks will re-open this issue.

Thanks a lot SF team for assistance.

🙏
