### ISSUE TITLE
JWT not terminated after logout lead to sensitive data exposure

### ISSUE THREAD

**Issue by karuneshsf** [sourcefuse/loopback4-microservice-catalog#2167]
**Describe the bug**
JWT not terminated after logout led to sensitive data exposure

**To Reproduce**
If the JWT token does not expire after the user logs out, it can lead to full account compromise once an attacker grasps the victim’s token since the token can be fetched from the browser history and logs.

**Expected behavior**
JWT should be terminated after logout

**Screenshots**
N/A
**Additional context**
N/A

**Comment by yeshamavani** [comment]
merged and released
