### ISSUE TITLE
@sourceloop/core documentation incomplete

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#254]
**Describe the bug**
As of now, the sourceloop/core readme only provides an overall idea of the module, lacking any of the specific details.

**Expected behavior**
The readme should provide details of all the components, sequences, etc the module provides.

**Comment by shubhamp-sf** [comment]
Moving it on https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1440
