### ISSUE TITLE
Add Open ID Connect Support to authentication-service

### ISSUE THREAD

**Issue by jamescrowley321** [sourcefuse/loopback4-microservice-catalog#265]
**Is your feature request related to a problem? Please describe.**
The authentication-service is missing many of the features of an OIDC provider.

**Describe the solution you'd like**
Find and integrate a library that will expose the features needed for the authentication-service to become a full OIDC provider.

**Comment by akshatdubeysf** [comment]
Pushed demo code in branch - oidc-test

Also more detailed specification - 
https://sourcefuse.atlassian.net/wiki/spaces/SOURCEFUSE/pages/3107389441/SourceLoop+OIDC+Service+DRAFT
