### ISSUE TITLE
Support of JOINs in repository calls

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#414]
**Is your feature request related to a problem? Please describe.**
As of now, including a related model in the repository calls results in two DB hits, there should be a way to avoid this using joins.

**Describe the solution you'd like**
There should be an optional parameter that when provided should fetch the related models using JOINS instead of separate DB calls - 

repo.find({include: [{relation:'child', join:true}]});

**Describe alternatives you've considered**
Other options that were considered were contributing to the loopback connector repo, but that would be time consuming, so  could try an extension for repositories instead.

**Comment by akshatdubeysf** [comment]
need to change interface for calling the join based provider

**Comment by shubhamp-sf** [comment]
Closing as [@loopback/sequelize](https://www.npmjs.com/package/@loopback/sequelize) serves the purpose.
