### ISSUE TITLE
Self onboarding flow for doctor/psychiatrist

### ISSUE THREAD

**Issue by chirappa-vishnupriya** [sourcefuse/loopback4-microservice-catalog#453]
We are having **doctor/psychiatrist self onboarding** flow
Where he can be onboard with the  details
First Name*
Last Name*
Phone Number*
Email*
**Medical Registration/License number***
**Typeof clinic/hospital like(Personal Clinic,Private Clinic,Private Hospital,Public Hospital)
Clinic/Hospital Name*** 
Address
City
Zipcode

After submit will ask for **6 digits OTP Verification** 
which will sent to Psychiatrist mobile
If its get verified successfully then he can **set the his password** Which will take two values 
**Create password
Confirm password** 
And submit he will able to login Portal

**Comment by akshatdubeysf** [comment]
Hi @chirappa-vishnupriya ,

Can you please elaborate on the issue you are facing or any difficulty in using this library.

**Comment by chirappa-vishnupriya** [comment]
doctor/psychiatrist  has signup option
where we will ask doctor/psychiatrist details this any normal user can have 
apart from normal user doctor/psychiatrist need to have medical license number where its a mandatory for doctor/psychiatrist 
we are maintaining clinics/hospital types as i mentioned in the comments i have 4 types of clinics
After submission of form need to Send OTP to doctor/psychiatrist registered mobile number that should be 6 digits
After successful verification of OTP he will set his password where we can use this at login time in portal

**Comment by akshatdubeysf** [comment]
So, you need the OTP verification part in the services, because everything else is provided by the current version of authentication service? OR you need help with how to use the sign up flow itself?

**Comment by chirappa-vishnupriya** [comment]
Yes I need OTP Verification
