### ISSUE TITLE
Support for Sourceloop Microservices in sourceloop/cli

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#481]
**Is your feature request related to a problem? Please describe.**
There should be a way to initiate a microservice based on one of the microservices provided in sourceloop

**Describe the solution you'd like**
Something like - 
ls microservice --ms=@sourceloop/authentication-service

**Additional context**
This can be done in the same way a local package is added

**Comment by Jyoti-13** [comment]
Done.
