### ISSUE TITLE
Github Readme Issues

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#529]
**Is your feature request related to a problem? Please describe.**
The READMEs of services have issues like - new services are missing, user-onboarding is stated to be a microservice, etc.

**Describe the solution you'd like**
These issues should be avoided in README, they make working with and understanding the libraries difficult.

**Comment by shubhamp-sf** [comment]
Moving it here: https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1440
