### ISSUE TITLE
Need Custom HTML Template to be paased

### ISSUE THREAD

**Issue by mithunraj31** [sourcefuse/loopback4-microservice-catalog#581]
**Is your feature request related to a problem? Please describe.**
       We are in neeed of custom Html template where we can use our components and stylings.

**Describe the solution you'd like**
       We could have a template to be passed from our component to the library

**Describe alternatives you've considered**
    None

**Additional context**
    The library is pretty awesome with all other required things.Looking forward for this custom template feature.

**Comment by akshatdubeysf** [comment]
@sumiter92
