### ISSUE TITLE
@sourceloop/authentication-service facebook & google login should work together

### ISSUE THREAD

**Issue by vaibhavkumar-sf** [sourcefuse/loopback4-microservice-catalog#622]
**Is your feature request related to a problem? Please describe.**
Generally both "Login with Google" & "Login with Facebook" are used together, so the authentication-service should support it.

**Describe the solution you'd like**
user_id in user_credentials table is unique .. it should be unique by composite-key (user_id, auth_provider)
Then in verification step, when doing .. 
`await this.userCredsRepository.findOne({
                where: {
                    userId: user.id,
                },
            });`
            filter by auth_provider too, 
             
![image](https://user-images.githubusercontent.com/30282624/160157269-6bf07f87-2697-49ce-8e93-e603dedc311a.png)
Also, please update readme file too for details of how any new user can easily use these facebook & google logins,
like : document that what is redirect_url in auth_clients table, it is different from 'FACEBOOK_AUTH_CALLBACK_URL' 'GOOGLE_AUTH_CALLBACK_URL'. .. 
Also, its better to add these values in example env or default env : 

FACEBOOK_AUTH_URL=https://www.facebook.com/v3.2/dialog/oauth
FACEBOOK_AUTH_TOKEN_URL=https://graph.facebook.com/v3.2/oauth/access_token

GOOGLE_AUTH_URL=https://accounts.google.com/o/oauth2/auth
GOOGLE_AUTH_TOKEN_URL=https://oauth2.googleapis.com/token

**Comment by vaibhavkumar-sf** [comment]
I've done it in my project, I can share details how to do it .. after this, we can use multiple SSO at once, but user entry will be only once .. like : vaibhav.kumar@sourcefuse.com can login / signup any method facebook / google / other .. he'll be 1 user in system.

**Comment by akshatdubeysf** [comment]
closing this as discussed
