### ISSUE TITLE
UI to Build Workflows

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#764]
**Is your feature request related to a problem? Please describe.**
Building a workflow using BPMN.js is very non-intuitive, there should be an easier way to build a workflow.

**Describe the solution you'd like**
A statement based UI that could build the workflow on basis of user inputs

**Comment by shubhamp-sf** [comment]
Fulfilled by https://github.com/sourcefuse/workflows-creator
