### ISSUE TITLE
Swagger authentication is not working in Service Designer 

### ISSUE THREAD

**Issue by arpitsourcefuse** [sourcefuse/loopback4-microservice-catalog#801]
**Describe the bug**
We want to apply the authentication on the swagger in service designer microservices. 
https://stg-app-service-builder.rmb-lab.jp/app-bundles-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/helm-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/workflow-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/user-tenant-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/artifactory-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/auth-service/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/report-facade/explorer/openapi.json
https://stg-app-service-builder.rmb-lab.jp/notification-service/explorer/openapi.json

**To Reproduce**
1) Open the above URLs in the browser 
2) The page will open without authentication

**Expected behavior**
While opening the URL, the user should be asked for authetication

**Comment by akshatdubeysf** [comment]
as discussed, this was fixed, hence closing the issue
