### ISSUE TITLE
Angular Libraries should be more themable

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#830]
**Describe the bug**
The Angular libraries have very restricted theming and styling support

**To Reproduce**
1. Install any one of the angular libraries from sourceloop
2. Try modifying the theme or style

**Expected behavior**
Should provide an easy way to customize the theme and styling of components

**Comment by yeshamavani** [comment]
Moved to https://github.com/sourcefuse/arc-ng-components/issues/23
