### ISSUE TITLE
Support for backstage integration in CLI

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-microservice-catalog#925]
**Describe the bug**
The cli should give an option to generate files needed for backstage integration.

**Expected behavior**
The generated monorepo and microservices should have mkdocs.yml and catalog-info.yml files to integrate with backstage.

**Additional context**
Refer this doc for more info - https://roadie.io/blog/backstage-monorepo-guide/

**Comment by yeshamavani** [comment]
Already done
